# fly.toml app configuration file generated for dynamidrive-python-apis on 2025-05-19T11:16:00Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "dynamidrive-python-apis"
primary_region = "sea"

[build]
    # Ensure dependencies are installed
    [build.args]
        PIP_NO_CACHE_DIR = "off"

[[services]]
    internal_port = 8000
    protocol = "tcp"
    [services.concurrency]
        type = "requests"
        hard_limit = 25
        soft_limit = 20
    [[services.ports]]
        port = 80
        handlers = ["http"]
    [[services.ports]]
        port = 443
        handlers = ["tls", "http"]
    [services.http_checks]
        interval = "10s"
        timeout = "2s"
        grace_period = "30s"

[vm]
    cpu_kind = "shared"
    cpus = 1
    memory_mb = 2048