# fly.toml app configuration file generated for dynamidrive-python-apis on 2025-05-19T10:47:00Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "dynamidrive-python-apis"
primary_region = "sea"

[build]

[[services]]
    internal_port = 8000  # Updated to match Uvicorn default
    protocol = "tcp"
    [services.concurrency]
        type = "requests"
        hard_limit = 25
        soft_limit = 20
    [[services.ports]]
        port = 80
        handlers = ["http"]
    [[services.ports]]
        port = 443
        handlers = ["tls", "http"]
    # Optional: Increase grace period for cold starts
    [services.http_checks]
        interval = "10s"
        timeout = "2s"
        grace_period = "30s"

[vm]
    cpu_kind = "shared"
    cpus = 1
    memory_mb = 2048  # Increased to 2GB for better performance with audio processing
