app = "audio-separation-api"
primary_region = "ord"

[build]
  builder = "docker"

[env]
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
